### ISSUE TITLE
Notifications deadline

### ISSUE THREAD

**Issue by futures-dev** [potykion/school_1329_server#5]
Нужно поле, которое говорит, после какого времени нотификации больше не нужно повторять.
Еще, кронтаб не поддерживает "раз в несколько недель", но видимо придется как-то на это забить.

**Comment by potykion** [comment]
>Нужно поле, которое говорит, после какого времени нотификации больше не нужно повторять.

Поле until сделаю.

>раз в несколько недель

Можно, но заебисто:
https://serverfault.com/a/633272
