### ISSUE TITLE
GET /api/event_comments lists comments for all events

### ISSUE THREAD

**Issue by futures-dev** [potykion/school_1329_server#6]
03-06 08:58:21.213 2813-2838/com.djavid.schoolapp D/OkHttp: --> GET https://school-1329.herokuapp.com/api/event_comments **?id=3** http/1.1
03-06 08:58:21.213 2813-2838/com.djavid.schoolapp D/OkHttp: Authorization: Token 455961d16a2371b428655255f6369d28a7debc7d
03-06 08:58:21.214 2813-2838/com.djavid.schoolapp D/OkHttp: --> END GET
03-06 08:58:21.328 2813-2838/com.djavid.schoolapp D/OkHttp: <-- 200 OK https://school-1329.herokuapp.com/api/event_comments?id=3 (114ms)
03-06 08:58:21.328 2813-2838/com.djavid.schoolapp D/OkHttp: Connection: keep-alive
03-06 08:58:21.328 2813-2838/com.djavid.schoolapp D/OkHttp: Server: gunicorn/19.7.1
03-06 08:58:21.328 2813-2838/com.djavid.schoolapp D/OkHttp: Date: Tue, 06 Mar 2018 08:58:23 GMT
03-06 08:58:21.328 2813-2838/com.djavid.schoolapp D/OkHttp: Content-Type: application/json
03-06 08:58:21.328 2813-2838/com.djavid.schoolapp D/OkHttp: Vary: Accept
03-06 08:58:21.328 2813-2838/com.djavid.schoolapp D/OkHttp: Allow: GET, POST, HEAD, OPTIONS
03-06 08:58:21.328 2813-2838/com.djavid.schoolapp D/OkHttp: X-Frame-Options: SAMEORIGIN
03-06 08:58:21.328 2813-2838/com.djavid.schoolapp D/OkHttp: Content-Length: 1042
03-06 08:58:21.328 2813-2838/com.djavid.schoolapp D/OkHttp: Via: 1.1 vegur
03-06 08:58:21.329 2813-2838/com.djavid.schoolapp D/OkHttp: [{"id":1,"text":"qq","created_by":"Gena","created":"2018-02-25T12:07:53.612672Z"},{"id":2,"text":"gg","created_by":"Gena","created":"2018-02-25T12:24:57.752459Z"},{"id":3,"text":"gg","created_by":"Gena","created":"2018-02-25T12:24:58.799122Z"},{"id":4,"text":"gg","created_by":"Gena","created":"2018-02-25T12:24:59.530558Z"},{"id":5,"text":"gg","created_by":"Gena","created":"2018-02-25T12:25:00.195494Z"},{"id":6,"text":"helllo darling ind your hat soo hight!!!!!!!!!","created_by":"Gena","created":"2018-02-25T12:34:38.512871Z"},{"id":7,"text":"helllo darling ind your hat soo hight!!!!!!!!!","created_by":"Gena","created":"2018-02-25T12:34:39.358280Z"},{"id":8,"text":"helllo darling ind your hat soo hight!!!!!!!!!","created_by":"Gena","created":"2018-02-25T12:34:47.083474Z"},{"id":9,"text":"WHEN??","created_by":"PHISICK","created":"2018-02-26T21:41:55.849602Z"},{"id":10,"text":"HELO!","created_by":"PHYSICKK","created":"2018-02-26T21:49:09.798428Z"},{"id":11,"text":"id","created_by":"TEST23","created":"2018-03-06T08:54:13.196480Z"}]
03-06 08:58:21.329 2813-2838/com.djavid.schoolapp D/OkHttp: <-- END HTTP (1042-byte body)

**Comment by potykion** [comment]
Use **event** parameter instead of **id**.
E.g. https://school-1329.herokuapp.com/api/event_comments?event=2
Docs: https://github.com/potykion/school_1329_server/wiki/Event-Comments#request-fields
